openapi: 3.1.0
info:
  title: Smart Watering Public API
  version: 3.0.0
paths:
  /healthz:
    get:
      tags:
      - system
      summary: Healthz
      operationId: healthz_healthz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Healthz Healthz Get
  /api/v3/auth/login:
    post:
      tags:
      - auth
      summary: Login
      operationId: login_api_v3_auth_login_post
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: true
              type: object
              title: Payload
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Login Api V3 Auth Login Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v3/auth/google:
    post:
      tags:
      - auth
      summary: Google Login
      operationId: google_login_api_v3_auth_google_post
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: true
              type: object
              title: Payload
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Google Login Api V3 Auth Google Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v3/auth/logout:
    post:
      tags:
      - auth
      summary: Logout
      operationId: logout_api_v3_auth_logout_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Logout Api V3 Auth Logout Post
      security:
      - HTTPBearer: []
  /api/v3/app/latest:
    get:
      tags:
      - app
      summary: Latest Release
      operationId: latest_release_api_v3_app_latest_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Latest Release Api V3 App Latest Get
  /api/v3/app/releases/{version_code}/download:
    get:
      tags:
      - app
      summary: Download Release
      operationId: download_release_api_v3_app_releases__version_code__download_get
      parameters:
      - name: version_code
        in: path
        required: true
        schema:
          type: integer
          title: Version Code
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v3/devices:
    get:
      tags:
      - device-cards
      summary: Project Device Catalog
      operationId: project_device_catalog_api_v3_devices_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties: true
                type: object
                title: Response Project Device Catalog Api V3 Devices Get
      security:
      - HTTPBearer: []
  /api/v3/devices/{device_id}/card:
    get:
      tags:
      - device-cards
      summary: Project Card
      operationId: project_card_api_v3_devices__device_id__card_get
      security:
      - HTTPBearer: []
      parameters:
      - name: device_id
        in: path
        required: true
        schema:
          type: string
          title: Device Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Project Card Api V3 Devices  Device Id  Card Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v3/devices/{device_id}/card/blocks/{block_id}:
    get:
      tags:
      - device-cards
      summary: Project Block
      operationId: project_block_api_v3_devices__device_id__card_blocks__block_id__get
      security:
      - HTTPBearer: []
      parameters:
      - name: device_id
        in: path
        required: true
        schema:
          type: string
          title: Device Id
      - name: block_id
        in: path
        required: true
        schema:
          type: string
          title: Block Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Project Block Api V3 Devices  Device Id  Card Blocks  Block
                  Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v3/devices/{device_id}/actions/{action}:
    post:
      tags:
      - device-cards
      summary: Execute Device Action
      operationId: execute_device_action_api_v3_devices__device_id__actions__action__post
      security:
      - HTTPBearer: []
      parameters:
      - name: device_id
        in: path
        required: true
        schema:
          type: string
          title: Device Id
      - name: action
        in: path
        required: true
        schema:
          type: string
          title: Action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
              title: Payload
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                title: Response Execute Device Action Api V3 Devices  Device Id  Actions  Action  Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
