#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "driver/gpio.h"

#define HX711_DOUT_PIN GPIO_NUM_19
#define HX711_SCK_PIN GPIO_NUM_3
#define STATUS_LED_PIN GPIO_NUM_1
#define START_PIN GPIO_NUM_10

#define WIFI_SSID "Vita"
#define WIFI_PASSWORD "Oskar390"

#define OFFSET_RAW 116274
#define SCALE_RAW_PER_GRAM 214.0f

#define READ_SAMPLES 1
#define READ_INTERVAL_MS 500
#define ZERO_DEADBAND_G 3.0f
#define WEIGHT_BUFFER_SIZE 5
#define DEFAULT_TARE_WEIGHT_G 0.0f
#define TARE_TOLERANCE_G 20.0f

#define ANOMALY_THRESHOLD_G 10.0f
#define ANOMALY_CONFIRM_COUNT 3
#define MAX_RAW_JUMP ((int32_t)(ANOMALY_THRESHOLD_G * SCALE_RAW_PER_GRAM))

#define CONTROL_START_DELAY_MS 2000
#define CONTROL_INTERVAL_MS 2000
#define LED_BLINK_MS 500
#define STOPPED_CHANGE_THRESHOLD_G 1.0f
#define STOPPED_CHANGE_DETECT_WINDOW_MS (CONTROL_INTERVAL_MS * 3)
#define WIFI_ONLINE_WINDOW_MS 30000

#define DEFAULT_DEEP_SLEEP_WAKEUP_INTERVAL_MIN 15U
#define MIN_DEEP_SLEEP_WAKEUP_INTERVAL_MIN 1U
#define MAX_DEEP_SLEEP_WAKEUP_INTERVAL_MIN 50U

#endif
